server:
  port: 9527
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gatewat-9527.com
    prefer-ip-address: true


info:
  app.name: zuul
  company.name: www.zuul.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  routes:
    mydept.serviceId: proe
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /hahaha
